from enum import Enum as StrEnum

class ErrorCode(StrEnum):
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_PHONE_OR_PASSWORD = "INVALID_PHONE_OR_PASSWORD"